version: '3.8'
services:
  # spark-master:
  #   image: ozlevka/spark-master-debian:2.2.0
  #   container_name: spark-master
  #   ports:
  #     - "8080:8080"
  #     - "7077:7077"
  #   environment:
  #     - INIT_DAEMON_STEP=setup_spark
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
  #   volumes: 
  #     - "${HOME}/spark-history:/history"
  # spark-worker-1:
  #   image: ozlevka/spark-worker-debian:2.2.0
  #   container_name: spark-worker-1
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  #     - "SPARK_WORKER_WEBUI_PORT=8081"
  #   volumes: 
  #     - "${HOME}/spark-history:/history"
  # spark-worker-2:
  #   image: ozlevka/spark-worker-debian:2.2.0
  #   container_name: spark-worker-2
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  #     - "SPARK_WORKER_WEBUI_PORT=8082"
  #   volumes: 
  #     - "${HOME}/spark-history:/history"
  
  history:
    image: ozlevka/spark-history-debian:2.2.0
    #command: /bin/sh -c 'SPARK_HISTORY_OPTS=" -Dspark.history.fs.logDirectory=file:/history" /spark/sbin/start-history-server.sh'
    #command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - "AWS_PROFILE=2auth"
      - "AWS_DEFAULT_REGION=us-west-2"
    # - "SPARK_MASTER=spark://spark-master:7077"
    volumes: 
      - "${HOME}/spark-history:/history"
      - "${HOME}/.aws:/root/.aws"
    ports:
      - 18080:18080

  # development:
  #   image: ozlevka/spark-dev-debian:2.2.0
  #   command: /bin/bash -c 'cd /home/vscode/dev && PYSPARK_DRIVER_PYTHON_OPTS="notebook --no-browser --ip=0.0.0.0 --port=7777" /spark/bin/pyspark --master spark://spark-master:7077 --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=file:///history/'
  #   #command: /bin/sh -c "while sleep 1000; do :; done"
  #   user: vscode
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  #   volumes:
  #     - "./:/home/vscode/dev"
  #     - "${HOME}/spark-history:/history"
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - 7777:7777
      
    
