version: '3'
services:
  spark-master:
    image: ozlevka/spark-master:3.0-debian
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: ozlevka/spark-worker:3.0-debian
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
  spark-worker-2:
    image: ozlevka/spark-worker:3.0-debian
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8082"
  
  development:
    image: ozlevka/spark-dev:3.0-debian
    #command: /bin/bash -c "PYSPARK_DRIVER_PYTHON_OPTS="notebook --no-browser --ip=0.0.0.0 --port=7777" /spark/bin/pyspark --master spark://spark-master:7077"
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    ports: 
      - 7777:7777
      - 7776:7776
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - "./:/home/vscode/dev"
    
